const crypto = require('crypto');
const { scoreProfile } = require('../engine/scorer');
const { getScoringProfile } = require('./userService');
const { productsForScore } = require('./productService');
const { logAudit } = require('./auditService');

// The decision rule shown on the report:
// at least one product unlocked -> APPROVED (for those products), otherwise NOT APPROVED.
function decisionFor(score, products) {
  if (products.eligible.length > 0) {
    return {
      outcome: 'APPROVED',
      summary: `Eligible for ${products.eligible.length} product(s), up to ${products.eligible[products.eligible.length - 1].product_name}.`,
    };
  }
  const nearest = products.locked[0];
  return {
    outcome: 'NOT APPROVED',
    summary: nearest
      ? `Score is ${nearest.points_away} points below the entry product (${nearest.product_name}).`
      : 'No products available.',
  };
}

// Collects EVERYTHING the PDF and the JSON export need, in one object.
// Keeping data-gathering separate from drawing means:
//  - the PDF code only draws (no DB calls inside)
//  - the JSON export and the PDF always show exactly the same numbers
async function buildReportData(userId, actor, format) {
  const profile = await getScoringProfile(userId); // throws 404 BEFORE any PDF bytes are sent
  const result = scoreProfile(profile);
  const products = await productsForScore(result.score);
  const generatedAt = new Date();

  // Short report id so a printed report can be matched to the audit log
  const reportId = `RPT-${crypto.randomBytes(4).toString('hex').toUpperCase()}`;

  await logAudit({ actor, action: 'REPORT_GENERATED', entity: 'user', entityId: userId,
    details: { report_id: reportId, format, score: result.score } });

  return {
    report_id: reportId,
    generated_at: generatedAt.toISOString(),
    applicant: {
      user_id: profile.user_id,
      age: profile.age,
      employment_status: profile.employment_status,
      education_level: profile.education_level,
      city_tier: profile.city_tier,
      monthly_income: Number(profile.monthly_income),
    },
    score: result.score,
    raw_points: result.raw_points,
    risk_band: result.risk_band,
    color: result.color,
    rule_version: result.rule_version,
    decision: decisionFor(result.score, products),
    components: result.components,
    breakdown: result.breakdown,
    top_positive: result.top_positive,
    top_negative: result.top_negative,
    missing_data: result.missing_data,
    products,
    disclaimer: 'This report is generated by a prototype alternative credit scoring system using synthetic data. '
      + 'It is not a legally binding credit decision. Final lending decisions remain with the lender.',
  };
}

module.exports = { buildReportData, decisionFor };